name: Pruebas MILFACE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Configurar Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Instalar dependencias Python
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install opencv-python-headless pytest
        
    - name: Correr Pruebas Unitarias con Pytest
      env:
        SECRET_KEY: test_secret_key_ci
        LLAVE_MAESTRA: test_llave_ci
        DATABASE_URL: milfaces.db
      run: |
        pytest
